#!/usr/bin/env python3
"""Generate compact Unicode tables used by the native YuE2 tokenizer.

The checked-in result keeps native builds independent of Python. Re-run this
script deliberately when updating the Unicode database version.
"""

from __future__ import annotations

import unicodedata


def ranges_for(predicate):
    result = []
    start = None
    previous = None
    for codepoint in range(0x110000):
        if predicate(codepoint):
            if start is None:
                start = codepoint
            previous = codepoint
        elif start is not None:
            result.append((start, previous))
            start = previous = None
    if start is not None:
        result.append((start, previous))
    return result


def valued_ranges(value_of):
    result = []
    start = 0
    previous = value_of(0)
    for codepoint in range(1, 0x110000):
        value = value_of(codepoint)
        if value != previous:
            if previous:
                result.append((start, codepoint - 1, previous))
            start = codepoint
            previous = value
    if previous:
        result.append((start, 0x10FFFF, previous))
    return result


def emit_pairs(name, values):
    print(f"inline constexpr CodepointRange {name}[] = {{")
    for first, last in values:
        print(f"    {{0x{first:X}, 0x{last:X}}},")
    print("};")


def main():
    letters = ranges_for(lambda cp: unicodedata.category(chr(cp)).startswith("L"))
    numbers = ranges_for(lambda cp: unicodedata.category(chr(cp)).startswith("N"))
    combining = valued_ranges(lambda cp: unicodedata.combining(chr(cp)))

    decomposition_data = []
    decompositions = []
    compositions = []
    for codepoint in range(0x110000):
        raw = unicodedata.decomposition(chr(codepoint))
        if not raw or raw.startswith("<"):
            continue
        sequence = tuple(int(part, 16) for part in raw.split())
        offset = len(decomposition_data)
        decomposition_data.extend(sequence)
        decompositions.append((codepoint, offset, len(sequence)))
        if len(sequence) == 2:
            normalized = unicodedata.normalize(
                "NFC", chr(sequence[0]) + chr(sequence[1])
            )
            if normalized == chr(codepoint):
                compositions.append((sequence[0], sequence[1], codepoint))

    print("// Generated by tools/generate_yue2_unicode_tables.py.")
    print(f"// Python unicodedata {unicodedata.unidata_version}.")
    print("#pragma once")
    print("#include <cstddef>")
    print("#include <cstdint>")
    print("namespace yue2::tokenizer_detail {")
    print("struct CodepointRange { std::uint32_t first; std::uint32_t last; };")
    print("struct CombiningRange { std::uint32_t first; std::uint32_t last; std::uint8_t value; };")
    print("struct Decomposition { std::uint32_t codepoint; std::uint16_t offset; std::uint8_t length; };")
    print("struct Composition { std::uint32_t first; std::uint32_t second; std::uint32_t result; };")
    print(f'inline constexpr const char unicode_version[] = "{unicodedata.unidata_version}";')
    emit_pairs("letter_ranges", letters)
    emit_pairs("number_ranges", numbers)
    print("inline constexpr CombiningRange combining_ranges[] = {")
    for first, last, value in combining:
        print(f"    {{0x{first:X}, 0x{last:X}, {value}}},")
    print("};")
    print("inline constexpr std::uint32_t decomposition_data[] = {")
    for index in range(0, len(decomposition_data), 12):
        values = ", ".join(f"0x{value:X}" for value in decomposition_data[index:index + 12])
        print(f"    {values},")
    print("};")
    print("inline constexpr Decomposition decompositions[] = {")
    for codepoint, offset, length in decompositions:
        print(f"    {{0x{codepoint:X}, {offset}, {length}}},")
    print("};")
    print("inline constexpr Composition compositions[] = {")
    for first, second, result in sorted(compositions):
        print(f"    {{0x{first:X}, 0x{second:X}, 0x{result:X}}},")
    print("};")
    print("} // namespace yue2::tokenizer_detail")


if __name__ == "__main__":
    main()
